[package]
name = "trojan"
version = "0.1.0"
authors = ["南浦月 <nanpuyue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.36"
clap = "2.33.1"
serde = { version = "1.0.114", features = ["serde_derive"] }
serde_json = "1.0.56"
sha2 = "0.9.1"
native-tls = "0.2.4"
tokio-native-tls = "0.1.0"
tokio = { version = "0.2.21", features = ["dns", "fs", "io-util", "macros", "stream", "sync", "tcp"] }
